name: App install and start

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  React-Build-Action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.REMOTE_SSH_HOST}}
          username: ${{REMOTE_SSH_USERNAME}}
          port: ${{REMOTE_SSH_PORT}}
          key: ${{REMOTE_SSH_KEY}}
          script: |
            whoami
            cd  /home/ubuntu/reactLearn/
            sudo git pull origin master
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install
            yarn build
