name: App install and start

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build API Server
        run: yarn build
